theme: jekyll-theme-Cayman
# Name of your site (displayed in the header)
name: Siddharth Chadha

# Short bio or description (displayed in the header)
description: Class of 2020. University of Illinois at Urbana-Champaign.

# Includes an icon in the footer for each username you enter
footer-links:
  email: "sidc97@gmail.com"
  github: SiddharthC97
  linkedin: siddharth-chadha-638881136
  telephone: 212-810-1766
