theme: jekyll-theme-Cayman
title: Siddharth Chadha
description: Aerospace Engineering.
description: Class of 2020. University of Illinois at Urbana-Champaign.

footer-link: linkedin: siddharth-chadha-638881136
