theme: jekyll-theme-Cayman
# Name of your site (displayed in the header)
title: Siddharth Chadha

# Short bio or description (displayed in the header)
description: Class of 2020. University of Illinois at Urbana-Champaign.

